name: Debug github action
on:
  workflow_dispatch:

jobs:
  Connection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        env:
          GITHUB_SECRETS: ${{ toJSON(secrets) }}
